---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: ansible_playbook
  playbook: default.yml
  hosts: all

platforms:
  - name: ubuntu
    driver_config:
      image: ubuntu:15.04

suites:
  - name: default
